# Generated by Django 5.0.1 on 2025-04-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='iob_title',
            new_name='job_title',
        ),
    ]
