# Generated by Django 5.0.1 on 2024-01-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectnote_projectfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectNote',
        ),
    ]
