# Generated by Django 5.0.1 on 2025-05-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
